services:
  db:
    image: registry.sedrehgroup.ir/postgis:latest
    restart: always
    environment:
      POSTGRES_DB: heydari_database
      POSTGRES_USER: sara_heydari
      POSTGRES_PASSWORD: sa50558094
    networks:
      - backend

  minio:
    image: registry.sedrehgroup.ir/minio:latest
    env_file:
      - .env
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:

      - ./minio_backup:/data
    command: server /data --console-address ":9001"
    networks:
      - backend



  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/bookstore
      - ./media:/media/media
      - ./shared:/shared
      - ./minio_backup:/minio_backup/data
    env_file:
      - .env
    depends_on:
      - db
      - minio
    networks:
      - backend


  geoserver:
    image: registry.sedrehgroup.ir/geoserver:2.24.2
    env_file:
      - .env
    restart: always
    volumes:
       - ./shared:/shared
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend

  nginx:
    image: registry.sedrehgroup.ir/nginx:latest
    container_name: nginx
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles:/staticfiles
      - ./media:/media
    depends_on:
      - web
    networks:
      - backend
networks:
  backend:

#networks:
#  main:
#    driver: bridge
